#!/usr/bin/env python3
# orior - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
# Catalog: VIZ-x-009
#
"""Turns build/bench/shadows.csv into a self-contained viewer page.

The bench dumps the SHA-256 dependency field collapsed along each of its axes. This reads those
projections and writes them into the page as compact JSON arrays, because an artifact cannot fetch
anything at run time: everything it draws has to ship with it.

    python examples/00_blob_viz_tools/build_shadow_view.py

Writes the page beside the template it is built from. The CSV is regenerated by building
src/engine/c/sha256/bench/bench_sac.cu into build/bench and running it there with

    18 45 64 shadow
"""

import csv
import os
import sys
import out_path
import generate_template

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(ROOT, "build", "bench", "shadows.csv")
TEMPLATE = os.path.join(HERE, "shadow_view_template.html")
TARGET = out_path.resolve("shadow_view.html")

ROUNDS = 64


def read_shadows(path):
    """Reads the dump into one dense array per projection, indexed [a][b][round]."""
    residue = [[0.0] * ROUNDS for _ in range(32)]
    inbit = [[0.0] * ROUNDS for _ in range(512)]
    outbit = [[0.0] * ROUNDS for _ in range(256)]
    word = [[[0.0] * ROUNDS for _ in range(8)] for _ in range(16)]

    with open(path, newline="") as handle:
        for row in csv.DictReader(handle):
            kind = row["kind"]
            a = int(row["a"])
            b = int(row["b"])
            at = int(row["round"]) - 1
            value = float(row["value"])
            if kind == "residue":
                residue[a][at] = value
            elif kind == "inbit":
                inbit[a][at] = value
            elif kind == "outbit":
                outbit[a][at] = value
            elif kind == "word":
                word[a][b][at] = value

    return residue, inbit, outbit, word


def trimmed(rows, places):
    """Rounds to the places actually needed, because full doubles triple the page for no pixels."""
    return [[round(value, places) for value in row] for row in rows]


def main():
    if not os.path.exists(SOURCE):
        sys.stderr.write("no build/bench/shadows.csv yet - build src/engine/c/sha256/bench/bench_sac.cu into build/bench and run it there with 18 45 64 shadow\n")
        return 1

    residue, inbit, outbit, word = read_shadows(SOURCE)

    payload = {
        "rounds": ROUNDS,
        "residue": trimmed(residue, 2),
        "inbit": trimmed(inbit, 1),
        "outbit": trimmed(outbit, 1),
        "word": [trimmed(plane, 1) for plane in word],
    }

    try:
        page = generate_template.assemble(TEMPLATE, payload)
    except generate_template.Refused as why:
        sys.stderr.write("%s: %s\n" % (os.path.basename(TEMPLATE), why))
        return 1

    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(page)

    print("wrote %s (%.1f KB)" % (TARGET, os.path.getsize(TARGET) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
