"""Turns src/bench/shadows.csv into a self-contained viewer page.

The bench dumps the SHA-256 dependency field collapsed along each of its axes. This reads those
projections and writes them into the page as compact JSON arrays, because an artifact cannot fetch
anything at run time: everything it draws has to ship with it.

    python tools/build_shadow_view.py

Writes the page beside the template it is built from. The CSV is regenerated by

    src/bench/bench_sac.exe 18 45 64 shadow
"""

import csv
import json
import os
import sys

import settings

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(ROOT, "src", "bench", "shadows.csv")
TEMPLATE = os.path.join(HERE, "voxel_view_template.html")
TARGET = os.path.join(HERE, "voxel_view.html")

ROUNDS = 64


def read_shadows(path):
    """Reads the dump into one dense array per projection, indexed [a][b][round]."""
    residue = [[0.0] * ROUNDS for _ in range(32)]
    inbit = [[0.0] * ROUNDS for _ in range(512)]
    outbit = [[0.0] * ROUNDS for _ in range(256)]
    word = [[[0.0] * ROUNDS for _ in range(8)] for _ in range(16)]

    with open(path, newline="") as handle:
        for row in csv.DictReader(handle):
            kind = row["kind"]
            a = int(row["a"])
            b = int(row["b"])
            at = int(row["round"]) - 1
            value = float(row["value"])
            if kind == "residue":
                residue[a][at] = value
            elif kind == "inbit":
                inbit[a][at] = value
            elif kind == "outbit":
                outbit[a][at] = value
            elif kind == "word":
                word[a][b][at] = value

    return residue, inbit, outbit, word


def trimmed(rows, places):
    """Rounds to the places actually needed, because full doubles triple the page for no pixels."""
    return [[round(value, places) for value in row] for row in rows]


def main():
    if not os.path.exists(SOURCE):
        sys.stderr.write("no shadows.csv yet - run: src/bench/bench_sac.exe 18 45 64 shadow\n")
        return 1

    residue, inbit, outbit, word = read_shadows(SOURCE)

    # Word pairs arrive as 16 planes of 8 and are flattened here and not in the page, because
    # the template now takes one shape for every field: a list of series over the depth axis.
    # For that reason it renders any parametric table and not only this one.
    pairs = []
    for plane in word:
        pairs.extend(trimmed(plane, 1))

    payload = {
        "depth": ROUNDS,
        "depthLabel": "round 1-64",
        "valueLabel": "deviation",
        "eyebrow": "Dependency field · rendered as a solid",
        "title": "SHA-256 Voxel Field",
        "blurb": ("The companion to the flat shadows: the same measured field built as a mesh you "
                  "can turn. Depth runs left to right as the 64 rounds; the other horizontal axis "
                  "is whichever way the field is being cut; height and color are the signed "
                  "deviation in standard errors. The cliff is the light cone - below it a message "
                  "word has not entered yet and flipping its bits changes nothing at all."),
        "noteTitle": "What the shapes are",
        "note": ("The long flat terrace at maximum height is not signal. It is "
                 "the region outside the causal cone, where every cell sits pinned at exactly minus "
                 "root n because the input cannot reach the output yet. Its edge is the message "
                 "schedule: word w cannot touch the state before round w+1, which draws the "
                 "staircase. The ground falls away after round 23, where every instrument in this "
                 "work goes flat and the field becomes white noise at every lag in both axes."),
        "settings": settings.collect(sys.argv[1:]),
        "fields": [
            {"key": "residue", "label": "Residue", "axis": "residue 0-31",
             "rows": trimmed(residue, 2)},
            {"key": "outbit", "label": "Output bits", "axis": "output bit",
             "rows": trimmed(outbit, 1)},
            {"key": "inbit", "label": "Input bits", "axis": "input bit",
             "rows": trimmed(inbit, 1)},
            {"key": "word", "label": "Word pairs", "axis": "W x state", "rows": pairs},
        ],
    }

    with open(TEMPLATE) as handle:
        page = handle.read()

    packed = json.dumps(payload, separators=(",", ":"))
    page = page.replace("/*VOXEL_DATA*/null", packed)

    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(page)

    print("wrote %s (%.1f KB)" % (TARGET, os.path.getsize(TARGET) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
