"""Turns src/bench/shadows.csv into a self-contained viewer page.

The bench dumps the SHA-256 dependency field collapsed along each of its axes. This reads those
projections and writes them into the page as compact JSON arrays, because an artifact cannot fetch
anything at run time: everything it draws has to ship with it.

    python tools/build_shadow_view.py

Writes the page beside the template it is built from. The CSV is regenerated by

    src/bench/bench_sac.exe 18 45 64 shadow
"""

import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOURCE = os.path.join(ROOT, "src", "bench", "shadows.csv")
TEMPLATE = os.path.join(HERE, "shadow_view_template.html")
TARGET = os.path.join(HERE, "shadow_view.html")

ROUNDS = 64


def read_shadows(path):
    """Reads the dump into one dense array per projection, indexed [a][b][round]."""
    residue = [[0.0] * ROUNDS for _ in range(32)]
    inbit = [[0.0] * ROUNDS for _ in range(512)]
    outbit = [[0.0] * ROUNDS for _ in range(256)]
    word = [[[0.0] * ROUNDS for _ in range(8)] for _ in range(16)]

    with open(path, newline="") as handle:
        for row in csv.DictReader(handle):
            kind = row["kind"]
            a = int(row["a"])
            b = int(row["b"])
            at = int(row["round"]) - 1
            value = float(row["value"])
            if kind == "residue":
                residue[a][at] = value
            elif kind == "inbit":
                inbit[a][at] = value
            elif kind == "outbit":
                outbit[a][at] = value
            elif kind == "word":
                word[a][b][at] = value

    return residue, inbit, outbit, word


def trimmed(rows, places):
    """Rounds to the places actually needed, because full doubles triple the page for no pixels."""
    return [[round(value, places) for value in row] for row in rows]


def main():
    if not os.path.exists(SOURCE):
        sys.stderr.write("no shadows.csv yet - run: src/bench/bench_sac.exe 18 45 64 shadow\n")
        return 1

    residue, inbit, outbit, word = read_shadows(SOURCE)

    payload = {
        "rounds": ROUNDS,
        "residue": trimmed(residue, 2),
        "inbit": trimmed(inbit, 1),
        "outbit": trimmed(outbit, 1),
        "word": [trimmed(plane, 1) for plane in word],
    }

    with open(TEMPLATE) as handle:
        page = handle.read()

    packed = json.dumps(payload, separators=(",", ":"))
    page = page.replace("/*SHADOW_DATA*/null", packed)

    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(page)

    print("wrote %s (%.1f KB)" % (TARGET, os.path.getsize(TARGET) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
