"""Stabiliser rank: the smallest number of stabiliser states that add up to a magic state.

    python tools/view/stabiliser_rank.py            the ranks, exactly
    python tools/view/stabiliser_rank.py --check    grade the machinery first

WHY THIS IS THE MEASURE THAT MATTERS HERE. This family spent a session establishing that MAGIC and
not entanglement is the resource: a perfect matching across a cut of 4096 qubits holds 2048 bits of
entanglement in a megabyte, Clifford gates conserve magic to 6.66e-16, and the T gate is exactly
free on the exact simulator at distance 0. All of that says what is cheap. None of it says what the
expensive thing COSTS.

Stabiliser rank does. Write a state as a sum of k stabiliser states and a Gottesman-Knill style
simulation runs in time proportional to k, because each term is separately cheap. So the minimum k,
written chi, IS the classical simulation cost of that state, and the exponential this family has
been circling lives in how chi grows with the number of T gates. That is the wall, stated as a
number rather than as a worry.

NO TOLERANCES ANYWHERE, AND THAT IS FORCED RATHER THAN PREFERRED. chi is the answer to "is this
vector in the span of those", and a span membership decided by a float comparison is a span
membership decided by a threshold somebody chose. Every amplitude in this file is an exact element
of Z[zeta_8], the ring generated by zeta = exp(i pi / 4):

    unnormalised H = [[1, 1], [1, -1]]      integer
    unnormalised S = diag(1, i)             i = zeta^2
    unnormalised CZ = diag(1, 1, 1, -1)     integer
    unnormalised |T> = (1, zeta)            the only place zeta itself enters

Normalisation is dropped throughout because chi is a question about SPANS, and a span does not care
about scale. That keeps every amplitude an algebraic integer, and linear algebra over the degree-4
field Q(zeta_8) then decides membership exactly. A rank is an integer or the machinery is broken;
there is no third outcome to tune.

WHAT IS AND IS NOT CLAIMED. The ranks below are computed by exhaustive search over the stabiliser
states at one, two and three qubits, whose counts are 6, 60 and 1080 and must match the closed form
2^n prod_{k=1}^{n} (2^k + 1) or the enumeration is wrong. Exhaustive means exhaustive at k = 1 and
k = 2; at three qubits the triples number 209 million and are not enumerated, a three-qubit
answer larger than 2 is reported as a LOWER BOUND and labelled as one.
"""

import argparse
import itertools
import os
import sys
from fractions import Fraction

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

# zeta_8 = exp(i pi / 4), so zeta^4 = -1 and {1, zeta, zeta^2, zeta^3} is a basis over Q.
ZERO = (Fraction(0),) * 4
ONE = (Fraction(1), Fraction(0), Fraction(0), Fraction(0))
ZETA = (Fraction(0), Fraction(1), Fraction(0), Fraction(0))
IMAGINARY = (Fraction(0), Fraction(0), Fraction(1), Fraction(0))
MINUS_ONE = (Fraction(-1), Fraction(0), Fraction(0), Fraction(0))

QUBITS_ENUMERATED = (1, 2, 3)


def add(left, right):
    return tuple(a + b for a, b in zip(left, right))


def negate(value):
    return tuple(-a for a in value)


def multiply(left, right):
    """Product in Z[zeta_8], by convolution folded with zeta^4 = -1."""
    wide = [Fraction(0)] * 7
    for at, a in enumerate(left):
        if a:
            for to, b in enumerate(right):
                if b:
                    wide[at + to] += a * b
    return tuple(wide[at] - wide[at + 4] if at + 4 < 7 else wide[at] for at in range(4))


def inverse(value):
    """The field inverse, by solving the 4x4 rational system that multiplication by `value` is.

    Q(zeta_8) is a degree-4 field over Q, so every nonzero element is invertible and the inverse is
    the solution of M_value y = 1 where M_value is multiplication as a linear map. Solved exactly
    with Fractions, an inverse is either returned or the element was zero.
    """
    columns = []
    for at in range(4):
        basis = [Fraction(0)] * 4
        basis[at] = Fraction(1)
        columns.append(multiply(value, tuple(basis)))
    rows = [[columns[column][row] for column in range(4)] for row in range(4)]
    target = [Fraction(1), Fraction(0), Fraction(0), Fraction(0)]

    for pivot in range(4):
        pick = next((row for row in range(pivot, 4) if rows[row][pivot]), None)
        if pick is None:
            raise ZeroDivisionError("no inverse, which means the element was zero")
        rows[pivot], rows[pick] = rows[pick], rows[pivot]
        target[pivot], target[pick] = target[pick], target[pivot]
        scale = rows[pivot][pivot]
        rows[pivot] = [one / scale for one in rows[pivot]]
        target[pivot] = target[pivot] / scale
        for row in range(4):
            if row != pivot and rows[row][pivot]:
                factor = rows[row][pivot]
                rows[row] = [a - factor * b for a, b in zip(rows[row], rows[pivot])]
                target[row] = target[row] - factor * target[pivot]
    return tuple(target)


def is_zero(value):
    return all(one == 0 for one in value)


def canonical(state):
    """The state scaled so its first nonzero amplitude is exactly 1.

    THE PROJECTIVE REPRESENTATIVE, because chi is about spans. Two states differing by a phase or
    any other scalar are the same point for this question, and canonicalising lets them be compared
    and deduplicated by equality rather than by a distance.
    """
    lead = next((one for one in state if not is_zero(one)), None)
    if lead is None:
        return state
    factor = inverse(lead)
    return tuple(multiply(one, factor) for one in state)


def apply_h(state, qubit, qubits):
    out = [ZERO] * len(state)
    for index in range(len(state)):
        if (index >> qubit) & 1:
            continue
        partner = index | (1 << qubit)
        low, high = state[index], state[partner]
        out[index] = add(low, high)
        out[partner] = add(low, negate(high))
    return tuple(out)


def apply_s(state, qubit, qubits):
    return tuple(multiply(one, IMAGINARY) if (index >> qubit) & 1 else one
                 for index, one in enumerate(state))


def apply_cz(state, left, right, qubits):
    return tuple(negate(one) if ((index >> left) & 1 and (index >> right) & 1) else one
                 for index, one in enumerate(state))


def stabiliser_states(qubits):
    """Every stabiliser state on `qubits` qubits, up to scale, by closure under the Clifford gates.

    THE COUNT IS THE CHECK. The number of n-qubit stabiliser states is exactly
    2^n prod_{k=1}^{n} (2^k + 1), which is 6, 60 and 1080 for one, two and three qubits. Reaching a
    different count means the closure is incomplete or the canonical form is collapsing distinct
    states, and either way every chi below would be wrong. So this is generated by closure and
    graded against the formula rather than trusted.
    """
    start = [ZERO] * (1 << qubits)
    start[0] = ONE
    seen = {canonical(tuple(start))}
    frontier = list(seen)

    while frontier:
        nxt = []
        for state in frontier:
            moves = []
            for qubit in range(qubits):
                moves.append(apply_h(state, qubit, qubits))
                moves.append(apply_s(state, qubit, qubits))
            for left in range(qubits):
                for right in range(left + 1, qubits):
                    moves.append(apply_cz(state, left, right, qubits))
            for move in moves:
                shaped = canonical(move)
                if shaped not in seen:
                    seen.add(shaped)
                    nxt.append(shaped)
        frontier = nxt
    return sorted(seen)


def expected_count(qubits):
    total = 1 << qubits
    for step in range(1, qubits + 1):
        total *= (1 << step) + 1
    return total


def magic_state(qubits):
    """|T>^(tensor qubits), unnormalised: amplitude zeta^(popcount) at each index."""
    out = []
    for index in range(1 << qubits):
        weight = bin(index).count("1")
        value = ONE
        for _ in range(weight):
            value = multiply(value, ZETA)
        out.append(value)
    return tuple(out)


def echelon(rows):
    """Row echelon form over Q(zeta_8), exactly. Returns the nonzero rows and the pivot columns."""
    rows = [list(row) for row in rows]
    pivots = []
    at = 0
    width = len(rows[0]) if rows else 0
    for column in range(width):
        pick = next((row for row in range(at, len(rows)) if not is_zero(rows[row][column])), None)
        if pick is None:
            continue
        rows[at], rows[pick] = rows[pick], rows[at]
        factor = inverse(rows[at][column])
        rows[at] = [multiply(one, factor) for one in rows[at]]
        for row in range(len(rows)):
            if row != at and not is_zero(rows[row][column]):
                scale = rows[row][column]
                rows[row] = [add(a, negate(multiply(scale, b)))
                             for a, b in zip(rows[row], rows[at])]
        pivots.append(column)
        at += 1
        if at == len(rows):
            break
    return rows[:at], pivots


def in_span(target, basis):
    """Is `target` in the span of `basis`, exactly. No tolerance, because none is needed."""
    rows, _pivots = echelon(list(basis))
    residue = list(target)
    for row in rows:
        column = next(at for at in range(len(row)) if not is_zero(row[at]))
        if not is_zero(residue[column]):
            scale = residue[column]
            residue = [add(a, negate(multiply(scale, b))) for a, b in zip(residue, row)]
    return all(is_zero(one) for one in residue)


def coefficients_for(target, basis):
    """The exact coefficients writing `target` over `basis`, or None if it is not in the span.

    THE WITNESS, WHICH A RANK ON ITS OWN IS NOT. "chi is 2" is a claim about a search; "chi is 2 and
    here are the two states and the two coefficients, and they add back to the target exactly" is a
    claim a stranger can check without rerunning the search. That is the same standard the constants
    table holds itself to, and Douglas asked for it directly: return the set that lets others
    reproduce it.
    """
    width = len(basis)
    rows = [[basis[column][row] for column in range(width)] + [target[row]]
            for row in range(len(target))]

    where = {}
    at = 0
    for column in range(width):
        pick = next((row for row in range(at, len(rows)) if not is_zero(rows[row][column])), None)
        if pick is None:
            continue
        rows[at], rows[pick] = rows[pick], rows[at]
        factor = inverse(rows[at][column])
        rows[at] = [multiply(one, factor) for one in rows[at]]
        for row in range(len(rows)):
            if row != at and not is_zero(rows[row][column]):
                scale = rows[row][column]
                rows[row] = [add(a, negate(multiply(scale, b)))
                             for a, b in zip(rows[row], rows[at])]
        where[column] = at
        at += 1

    # A row that is zero across the basis but nonzero in the target column is an inconsistency,
    # which is exactly "not in the span".
    for row in rows:
        if all(is_zero(one) for one in row[:width]) and not is_zero(row[width]):
            return None

    return [rows[where[column]][width] if column in where else ZERO for column in range(width)]


def combine(basis, weights):
    """The exact linear combination, for checking a witness adds back to what it claims."""
    out = [ZERO] * len(basis[0])
    for vector, weight in zip(basis, weights):
        for at, one in enumerate(vector):
            out[at] = add(out[at], multiply(one, weight))
    return tuple(out)


def tensor(left, right, right_qubits):
    """The tensor product of two states, as a state on the combined register."""
    out = []
    for high in range(len(left)):
        for low in range(len(right)):
            out.append(multiply(left[high], right[low]))
    return tuple(out)


def chi_of(target, states, cap=2):
    """(chi, exhausted) for `target` against `states`, searching k up to `cap`.

    `exhausted` says whether the search was complete. A result at the cap with nothing found is a
    LOWER BOUND and is reported as one rather than as an answer, because the triples at three
    qubits number 209 million and are not enumerated here.
    """
    shaped = canonical(target)
    if shaped in set(states):
        return 1, True, [shaped]
    if cap < 2:
        return cap + 1, False, None

    # THE SEARCH IS REORDERED AND THE IDENTITY IS WORTH STATING, because the obvious loop
    # re-echelons the same basis 580,000 times at three qubits and does not finish.
    #
    #     psi in span{s_left, s_right}   <=>   s_right in span{psi, s_left}
    #
    # Forward: psi = a s_left + b s_right with b nonzero gives s_right = (psi - a s_left)/b. Back:
    # s_right = c psi + d s_left with c nonzero gives psi = (s_right - d s_left)/c, and c zero
    # would make s_right a multiple of s_left, which canonical forms being distinct rules out.
    #
    # So the two-dimensional space span{psi, s_left} is echeloned ONCE per left and every right is
    # tested against it, with the reduction abandoned at the first surviving coordinate.
    for left in range(len(states)):
        rows, pivots = echelon([shaped, states[left]])
        if len(rows) < 2:
            continue
        for right in range(len(states)):
            if right == left:
                continue
            residue = list(states[right])
            for row, column in zip(rows, pivots):
                if not is_zero(residue[column]):
                    scale = residue[column]
                    residue = [add(a, negate(multiply(scale, b)))
                               for a, b in zip(residue, row)]
            if all(is_zero(one) for one in residue):
                return 2, True, [states[left], states[right]]
    return 3, False, None


def _report():
    print("")
    print("  Stabiliser rank of the magic states, exactly, over Q(zeta_8).")
    print("")
    print("  %7s %12s %10s %10s %26s"
          % ("qubits", "stabilisers", "chi", "witness", "what that means"))

    found = {}
    for qubits in QUBITS_ENUMERATED:
        states = stabiliser_states(qubits)
        target = magic_state(qubits)
        value, exhausted, witness = chi_of(target, states)

        # THE WITNESS IS CHECKED HERE AND NOT TAKEN ON THE SEARCH'S WORD. The coefficients are
        # solved for exactly and recombined, and the result must equal the target to the last
        # coordinate. A search that returns the wrong pair would otherwise report a rank.
        verdict = "n/a"
        if witness is not None:
            weights = coefficients_for(target, witness)
            verdict = "adds back" if (weights is not None
                                      and combine(witness, weights) == target) else "WRONG"
            found[qubits] = (witness, weights)

        shown = "%d" % value if exhausted else ">= %d" % value
        note = "exact, search complete" if exhausted else "lower bound, pairs exhausted"
        print("  %7d %12d %10s %10s %26s" % (qubits, len(states), shown, verdict, note))

    # THE UPPER BOUND COMES FREE FROM THE TENSOR PRODUCT AND NEEDS NO SEARCH AT ALL. If
    # psi = sum a_i s_i and phi = sum b_j t_j then psi tensor phi = sum a_i b_j (s_i tensor t_j),
    # and a tensor product of stabiliser states IS a stabiliser state, so
    # chi(psi tensor phi) <= chi(psi) chi(phi). That brackets the three qubit answer between the
    # exhausted pair search below and this construction above, and the construction is VERIFIED by
    # rebuilding the target from it rather than argued.
    if 1 in found and 2 in found:
        small, small_weights = found[1]
        mid, mid_weights = found[2]
        pieces = []
        weights = []
        for left, a in zip(small, small_weights):
            for right, b in zip(mid, mid_weights):
                pieces.append(tensor(left, right, 2))
                weights.append(multiply(a, b))
        rebuilt = combine(pieces, weights)
        target = magic_state(3)
        print("")
        print("  the tensor bound: chi(|T>^3) <= chi(|T>) chi(|T>^2) = %d x %d = %d"
              % (len(small), len(mid), len(pieces)))
        print("  built explicitly from the two witnesses above and rebuilt the target: %s"
              % ("yes" if rebuilt == target else "NO"))
        print("  every term is a tensor product of stabiliser states, so every term is one: %s"
              % all(canonical(one) in set(stabiliser_states(3)) for one in pieces))
        print("")
        print("  SO THE THREE QUBIT ANSWER IS BRACKETED, 3 <= chi(|T>^3) <= %d. The lower bound is"
              % len(pieces))
        print("  the exhausted pair search and the upper bound is the construction, and neither is")
        print("  an estimate. The triples are not enumerated, so the exact value inside that")
        print("  bracket is open and is left open rather than guessed at.")

    print("")
    print("  The stabiliser count must be 2^n prod (2^k + 1), which is 6, 60 and 1080. It is")
    print("  generated by closure under H, S and CZ and graded against that formula in --check,")
    print("  because a missing stabiliser state would make every chi above too large.")
    print("")
    print("  WHY chi IS THE COST. A state written as k stabiliser terms simulates in time")
    print("  proportional to k, each term being cheap by Gottesman-Knill. So chi is the classical")
    print("  simulation cost, and its growth in the number of T gates is where this family's")
    print("  exponential actually lives. Entanglement was never it: 2048 bits of entanglement fit")
    print("  in a megabyte at 4096 qubits, and Clifford gates conserve magic to 6.66e-16.")
    print("")
    return 0


def _check():
    lines = []
    failed = 0

    # THE RING. zeta^4 must be -1 and zeta^8 must be 1, or every amplitude is in the wrong field.
    power = ONE
    for _ in range(4):
        power = multiply(power, ZETA)
    lines.append("  zeta^4 = %s, wanted -1" % (power,))
    if power != MINUS_ONE:
        lines.append("    FAIL zeta^4 is not -1, so this is not Q(zeta_8)")
        failed += 1
    for _ in range(4):
        power = multiply(power, ZETA)
    if power != ONE:
        lines.append("    FAIL zeta^8 is not 1")
        failed += 1

    # zeta^2 must be the imaginary unit, since S is built from it.
    squared = multiply(ZETA, ZETA)
    lines.append("  zeta^2 = %s, wanted i" % (squared,))
    if squared != IMAGINARY:
        lines.append("    FAIL zeta^2 is not i, so the S gate is wrong")
        failed += 1

    # THE FIELD INVERSE, on an element with every coordinate live a lucky zero cannot pass it.
    awkward = (Fraction(1), Fraction(2), Fraction(-3), Fraction(5))
    back = multiply(awkward, inverse(awkward))
    lines.append("  a 4-coordinate element times its inverse is %s" % (back,))
    if back != ONE:
        lines.append("    FAIL the field inverse is wrong, so every rank here is wrong")
        failed += 1

    # THE ENUMERATION, against the closed form. This is the load-bearing check.
    for qubits in QUBITS_ENUMERATED:
        states = stabiliser_states(qubits)
        want = expected_count(qubits)
        lines.append("  %d qubit stabiliser states: %d, formula says %d"
                     % (qubits, len(states), want))
        if len(states) != want:
            lines.append("    FAIL the closure is incomplete or the canonical form is collapsing")
            lines.append("         distinct states, and either way every chi is wrong")
            failed += 1

    # THE POSITIVE CONTROL. A stabiliser state must have chi exactly 1, or the search cannot find
    # the easy case and nothing it reports about a hard case means anything.
    states = stabiliser_states(2)
    value, exhausted, _witness = chi_of(states[7], states)
    lines.append("  chi of a stabiliser state itself: %d (search complete %s)"
                 % (value, exhausted))
    if value != 1:
        lines.append("    FAIL a stabiliser state does not have rank 1")
        failed += 1

    # THE NEGATIVE CONTROL. chi can never exceed 2^n, because the computational basis states ARE
    # stabiliser states and they span the whole space. A search returning more than that is
    # searching wrongly rather than finding something.
    for qubits in (1, 2):
        states = stabiliser_states(qubits)
        basis = []
        for index in range(1 << qubits):
            vector = [ZERO] * (1 << qubits)
            vector[index] = ONE
            basis.append(canonical(tuple(vector)))
        missing = [one for one in basis if one not in set(states)]
        lines.append("  %d qubit computational basis inside the stabiliser set: %s"
                     % (qubits, not missing))
        if missing:
            lines.append("    FAIL a computational basis state is not in the enumeration, so the")
            lines.append("         2^n ceiling on chi does not hold and the search is unbounded")
            failed += 1

    # AND SPAN MEMBERSHIP MUST REJECT SOMETHING, or in_span is a function that says yes.
    two = stabiliser_states(1)
    plus = canonical((ONE, ONE))
    zero = canonical((ONE, ZERO))
    lines.append("  in_span rejects |+> against span{|0>}: %s" % (not in_span(plus, [zero])))
    if in_span(plus, [zero]):
        lines.append("    FAIL span membership accepts a vector outside the span")
        failed += 1
    lines.append("  in_span accepts |+> against span{|0>, |1>}: %s"
                 % in_span(plus, [zero, canonical((ZERO, ONE))]))
    if not in_span(plus, [zero, canonical((ZERO, ONE))]):
        lines.append("    FAIL span membership rejects a vector that is in the span")
        failed += 1
    if len(two) != 6:
        lines.append("    FAIL there are not 6 single qubit stabiliser states")
        failed += 1

    print("")
    for line in lines:
        print(line)
    print("")
    print("%d check(s) failed" % failed)
    print("")
    return 1 if failed else 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="stabiliser rank of the magic states, exactly")
    parser.add_argument("--check", action="store_true")
    parsed = parser.parse_args()
    sys.exit(_check() if parsed.check else _report())
