#!/usr/bin/env python3
# MMgr - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
"""Write src/pow5/pow5.h: the powers of five a decimal conversion needs, and nothing else.

A decimal value is mant * 10^ex, and ten to the ex is five to the ex times two to the ex. The twos
never need arithmetic - they are the exponent field of the result, and putting one there is an add.
The fives are what has to be carried, and they are the same handful of numbers on every call, so
they belong in a table rather than in a loop that rebuilds them.

Each entry is five to a power of two, held as a 128 bit fraction with the top bit set and its own
binary exponent, so any exponent up to 511 is the product of at most nine of them. The reciprocals
are here too, which is what keeps a negative exponent a multiply instead of a division.

Truncated rather than rounded, on purpose. A truncated entry is never larger than the true power,
so the product is never larger than the true product, and the sticky bit that decides a tie is
never wrongly clear. Rounding the entries would put an error either side of the true value and the
tie would stop being decidable from the bits that are there.
"""

import pathlib

STEPS = 9  # 5^1, 5^2, 5^4 ... 5^256, so any exponent below 512
BITS = 128
ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "src" / "pow5" / "pow5.h"


def norm(num, den):
    """The 128 bit fraction just below num/den, with the binary exponent that goes with it."""
    s = BITS - 1 - (num.bit_length() - den.bit_length())

    def at(shift):
        return (num << shift) // den if shift >= 0 else num // (den << -shift)

    while at(s) < (1 << (BITS - 1)):
        s += 1
    while at(s) >= (1 << BITS):
        s -= 1
    return at(s), -s


def table(name, brief, recip):
    """One table, as C."""
    out = ["/** @brief %s */" % brief, "static const MmgrPow5 %s[MMGR_POW5_STEPS] = {" % name]
    for i in range(STEPS):
        p = 5 ** (1 << i)
        v, e = norm(1, p) if recip else norm(p, 1)
        out.append(
            # The pad goes after the closing brace, not inside it. clang-format normalises the
            # spacing within a brace list and aligns the trailing comments after it, so padding
            # the number is undone and padding here is what survives - and a generated header
            # that comes back from the formatter changed reads as one somebody edited by hand.
            "    {0x%016XULL, 0x%016XULL, %d},%s/* 5^%s%-3d */"
            % (v >> 64, v & ((1 << 64) - 1), e, " " * (5 - len(str(e))), "-" if recip else "", 1 << i)
        )
    out.append("};")
    return out


lines = [
    "// MMgr - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>",
    "// SPDX-License-Identifier: AGPL-3.0-or-later",
    "//",
    "// Generated by tools/dev_env/gen_pow5.py. Editing this by hand is undone the next time anyone",
    "// runs the generator, and `harness.py generated` will say so before that happens.",
    "#ifndef MMGR_POW5_H",
    "#define MMGR_POW5_H",
    "",
    '#include "config/mmgr_config.h"',
    "",
    "MMGR_INCIPE_DECLS",
    "",
    "/**",
    " * @file pow5.h",
    " * @brief The powers of five a decimal conversion needs.",
    " *",
    " * A decimal value is mant * 10^ex. Ten to the ex is five to the ex times two to the ex, and the",
    " * twos are free: a power of two is the exponent field, so applying one is an add to that field",
    " * and cannot round. Only the fives need carrying, and they are the same numbers every time.",
    " *",
    " * Each entry is five to a power of two as a 128 bit fraction with the top bit set, beside the",
    " * binary exponent that goes with it. Any exponent below 512 is the product of at most nine of",
    " * them, so the loop that used to run four hundred times runs nine.",
    " *",
    " * The reciprocals are the second table. A negative exponent multiplies by one of those rather",
    " * than dividing, and division is the one operation this library does not want in a hot path.",
    " *",
    " * Truncated, not rounded. A truncated entry is never above the true power, so a product is",
    " * never above the true product, and the bit that decides a tie is never wrongly clear.",
    " *",
    " * No dispatch table, because there is nothing to dispatch. Every other module's surface is a run",
    " * of function pointers addressed by offset; this one has no entries at all - it is two constant",
    " * arrays and the two numbers that describe their shape. A namespace of no members is not a",
    " * narrower surface, it is an empty struct the layout assert cannot check.",
    " */",
    "",
    "/** @brief How many doublings the tables carry. */",
    "#define MMGR_POW5_STEPS %d" % STEPS,
    "",
    "/** @brief Largest decimal exponent the tables can reach. */",
    "#define MMGR_POW5_MAX ((1 << MMGR_POW5_STEPS) - 1)",
    "",
    "/** @brief One power of five: a 128 bit fraction, top bit set, and its binary exponent. */",
    "typedef struct",
    "{",
    "    mmgr_u64 hi;",
    "    mmgr_u64 lo;",
    "    int e2;",
    "} MmgrPow5;",
    "",
]
lines += table("mmgr_pow5_up", "Five to the power of two of the index.", False)
lines.append("")
lines += table("mmgr_pow5_down", "And the reciprocals, so a negative exponent never divides.", True)
lines += [
    "",
    'MMGR_STATIC_ASSERT(MMGR_POW5_MAX >= 511, "the tables do not reach the exponents a double can carry");',
    "",
    "MMGR_FINIS_DECLS",
    "",
    "#endif",
]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote %s" % OUT.relative_to(ROOT).as_posix())
