#!/usr/bin/env python3
# MMgr - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
"""Emit src/ascii_persona_bitorum/{ascii_persona_bitorum.h,ascii_persona_bitorum.c,CMakeLists.txt}.

Bitmaps, not range chains: one shift and one and answers any class, and every class costs the same.

Sixteen bytes rather than two uint64, because this library builds at MMGR_WORD_BITS 16 as well as
64 and a 64-bit shift is a called routine there. Indexing bytes is the same one load, one shift, one
and on every width, and needs no per-width spelling of the constants.

A class is named by an index and answered by the .c that holds the masks. The masks used to be ten
static const objects in the header, which is a hundred and sixty bytes of them in every translation
unit that wanted to ask one question, and their initializer macros stayed in the header after the
storage moved out - ten names in the global preprocessor namespace of every consumer, for the
benefit of one file. Both now live in the .c, which is the only thing that reads them.
"""

import pathlib

# HERE is mmgr/tools/dev_env, LIB is mmgr. Same convention as readclean.py, so the generator runs
# from anywhere.
HERE = pathlib.Path(__file__).resolve().parent
LIB = HERE.parent.parent
OUT = LIB / "src" / "ascii_persona_bitorum"
OUT.mkdir(parents=True, exist_ok=True)

BANNER = """// MMgr - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
//
// Generated by tools/dev_env/gen_ascii_persona_bitorum.py. Editing this by hand is undone the next
// time anyone runs the generator, and `harness.py generated` will say so before that happens."""


def num(c):
    return 0x30 <= c <= 0x39


def upper(c):
    return 0x41 <= c <= 0x5A


def lower(c):
    return 0x61 <= c <= 0x7A


def alpha(c):
    return upper(c) or lower(c)


def alnum(c):
    return alpha(c) or num(c)


def space(c):
    return c == 0x20 or 0x09 <= c <= 0x0D


def punct(c):
    return 0x21 <= c <= 0x7E and not alnum(c)


def hexd(c):
    return num(c) or (0x41 <= c <= 0x46) or (0x61 <= c <= 0x66)


def prnt(c):
    return 0x20 <= c <= 0x7E


def ctrl(c):
    return c < 0x20 or c == 0x7F


# In enum order. These are the values of MmgrAsciiClass, so this list is API: reordering it
# renumbers the classes under every caller that already compiled against them.
CLASSES = [
    ("NUM", num, "0-9"),
    ("ALPHA", alpha, "A-Z a-z"),
    ("ALNUM", alnum, "0-9 A-Z a-z"),
    ("UPPER", upper, "A-Z"),
    ("LOWER", lower, "a-z"),
    ("HEX", hexd, "0-9 A-F a-f"),
    ("PUNCT", punct, "printable, not alphanumeric, not space"),
    ("SPACE", space, "space tab newline vtab formfeed return"),
    ("CTRL", ctrl, "below space, and DEL"),
    ("PRINT", prnt, "space through ~"),
]


def bytes_of(pred):
    b = [0] * 16
    for c in range(128):
        if pred(c):
            b[c >> 3] |= 1 << (c & 7)
    return b


masks = "\n\n".join(
    "/** @brief %s */\n#define MMGR_ASCII_%s_INIT                                            \\\n    {{%s}}"
    % (doc, name, ", ".join("0x%02X" % x for x in bytes_of(pred)))
    for name, pred, doc in CLASSES
)

# The first is pinned to 0 so the numbering is written down rather than implied.
enum = "\n".join("    MMGR_ASCII_%s%s," % (n, " = 0" if i == 0 else "") for i, (n, _, _) in enumerate(CLASSES))

rows = "\n".join("    [MMGR_ASCII_%s] = MMGR_ASCII_%s_INIT," % (n, n) for n, _, _ in CLASSES)

HDR = (BANNER + """
#ifndef MMGR_ASCII_PERSONA_BITORUM_H
#define MMGR_ASCII_PERSONA_BITORUM_H

#include "config/mmgr_config.h"

MMGR_INCIPE_DECLS

/**
 * @file ascii_persona_bitorum.h
 * @brief Character classes as bitmaps. One shift and one and answers any of them.
 *
 * Every class costs the same. There is no cheap class and no expensive one, and no range chain
 * anywhere. ws() was six compares and a branch. digit() was two. Neither is now.
 *
 * Sixteen bytes, not two uint64. The obvious spelling is a pair of 64-bit halves indexed by bit 6,
 * and on x86 that is fine. This library also builds at MMGR_WORD_BITS 16, where a 64-bit shift is a
 * called routine and a 64-bit constant is four loads. Byte indexing is one load, one shift and one
 * and on every width, and needs no per-width spelling of the constants.
 *
 * Generated by tools/dev_env/gen_ascii_persona_bitorum.py from the predicates. These are exactly the
 * constants nobody can check by eye - the first three written out by hand had 'Z' missing from
 * ALPHA, and space, DEL and 0x1F wrongly in PUNCT.
 *
 * Bytes at or above 0x80 are in no class.
 *
 * The table is the whole surface. There are no free functions to call.
 */

/** @brief A 128-bit character class. */
typedef struct
{
    uint8_t b[16];
} MmgrAsciiMask;

MMGR_STATIC_ASSERT(sizeof(MmgrAsciiMask) == 16u, "an ASCII class mask is exactly 128 bits");

/** @brief Which class is being asked about. */
typedef enum
{
%(enum)s
    MMGR_ASCII_CLASSES
} MmgrAsciiClass;

/**
 * @brief What a class test is given.
 *
 * Public, and in the header, because the caller is what builds it. Both members are const: nothing
 * writes to a config once the caller has built it, and the compound literal is gone before there is
 * code that could.
 *
 * Not the module's context. AsciiCtx is what the body works with and it is file local in the .c.
 */
typedef struct
{
    const MmgrAsciiClass k; /**< The class being asked about. */
    const uint8_t c;        /**< The byte. */
} AsciiCfg;

/** @brief Dispatch table. Addressed by offset, so the layout is asserted below. */
typedef struct
{
    mmgr_bool (*in)(const AsciiCfg *c);
} AsciiPersonaBitorumNs;
MMGR_NS_LAYOUT(AsciiPersonaBitorumNs, in);

/** @name The entries the table points at.
 *  @brief Nameable so a static const table can name them, and for no other reason. The table is
 *         still the whole surface: call through it.
 *
 *  Neither the masks nor the macros that spell them cross this header. A class is named by an
 *  index and answered by the file that holds them, so no translation unit that asks the question
 *  carries a copy of the answer, and none of them has ten more names to avoid.
 *  @{ */
mmgr_bool mmgr_ascii_in(const AsciiCfg *c);

/**
 * @brief The byte a class test is asked about, and nothing that merely converts to one.
 *
 * uint8_t, not char. Whether char is signed is the implementation's to decide, so a byte at or
 * above 0x80 arrives negative on one target and positive on the next, and a macro that quietly
 * cast it would make the same source mean two things. The caller says which it meant.
 */
#define MMGR_ASCII_IS_BYTE(x_) ((void)_Generic((x_), uint8_t: 0))

/**
 * @brief Is @p c_ in class @p k_.
 *
 * Positional in, so the struct and the designators never reach a call site, and the type of every
 * argument is settled where the call is written.
 */
#define mmgr_ascii_in(k_, c_) (MMGR_ASCII_IS_BYTE(c_), ascii.in(&(AsciiCfg){.k = (k_), .c = (c_)}))
/** @} */

/**
 * @brief Module namespace.
 *
 * static const, like every other module's. gcc devirtualizes a call through one down to the
 * inlined body and cannot do that through an extern one, where the table is in another
 * translation unit and every call is a load and an indirect jump.
 */
MMGR_NS AsciiPersonaBitorumNs ascii MMGR_UNUSED = {
    .in = mmgr_ascii_in,
};

MMGR_FINIS_DECLS

#endif
""") % {"enum": enum}

SRC = (BANNER + """
#include "ascii_persona_bitorum/ascii_persona_bitorum.h"

/**
 * @file ascii_persona_bitorum.c
 * @brief The class masks, and the one question asked of them.
 *
 * The masks are here and nowhere else, and so are the macros that spell them. This is the only
 * translation unit that holds them and the only one that can name them, which is what makes the
 * header's claim true: a module that wants to know whether a byte is a digit includes a
 * declaration and gets no copy of the answer and no ten new names it has to avoid.
 *
 * A macro is not storage, so the ten that used to sit in the header cost no bytes. They cost the
 * global preprocessor namespace of every translation unit downstream of the header, which is every
 * consumer of the library, for the benefit of this one file.
 */

%(masks)s

/** @brief The classes, in the order MmgrAsciiClass names them. */
static const MmgrAsciiMask s_class[MMGR_ASCII_CLASSES] = {
%(rows)s
};

/**
 * @brief One class test.
 *
 * File local and staying that way. AsciiCfg in the header wears the same two fields and is not
 * this: that one is what the caller hands over, this one is what the body works with.
 */
typedef struct
{
    MmgrAsciiClass k; /**< The class being asked about. */
    uint8_t c;        /**< The byte. */
} AsciiCtx;

/**
 * @brief Is the byte in the class.
 * @param x The test.
 * @return MMGR_TRUE if it is. Bytes at or above 0x80 are in no class.
 *
 * One load, one shift and one and, on every width. An index past the last class is a caller that
 * has not decided what it is asking.
 */
MMGR_INLINE mmgr_bool ascii_in(const AsciiCtx *x)
{
    MMGR_ASSERT(x->k < MMGR_ASCII_CLASSES, "no such character class");

    const MmgrAsciiMask *const m = &s_class[x->k];
    return (mmgr_bool)((x->c < 0x80u) && (((m->b[x->c >> 3] >> (x->c & 7u)) & 1u) != 0u));
}

/* The namespace is a table of function pointers with the caller's config in their types, so this
   is what it points at. It builds the context and hands it to the body above.

   Parenthesised because the header defines a macro of this name for the call site, and the
   identifier here would otherwise sit immediately before a parenthesis and be taken for an
   invocation of it.

   It is nameable rather than file local because a static const table in the header has to be able
   to point at it, and a static const table is what gcc devirtualizes. Through an extern one every
   call from another translation unit is a load of the table, a load of the entry, and an indirect
   call it cannot see through. */

mmgr_bool (mmgr_ascii_in)(const AsciiCfg *c)
{
    return MMGR_CALL(ascii_in, AsciiCtx, .k = c->k, .c = c->c);
}
""") % {"masks": masks, "rows": rows}

CMAKE = """# MMgr - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
#
# Generated by tools/dev_env/gen_ascii_persona_bitorum.py.

# The masks are file local. A header full of static const tables is a copy of all of them in
# every translation unit that wanted to ask one question.
mmgr_add_module(ascii_persona_bitorum
  SOURCES ascii_persona_bitorum.c
)
"""

for rel, text in (
    ("ascii_persona_bitorum.h", HDR),
    ("ascii_persona_bitorum.c", SRC),
    ("CMakeLists.txt", CMAKE),
):
    p = OUT / rel
    p.write_text(text, encoding="utf-8")
    print("wrote %s" % p.relative_to(LIB).as_posix())

for name, pred, _ in CLASSES:
    b = bytes_of(pred)
    lo = int.from_bytes(bytes(b[:8]), "little")
    hi = int.from_bytes(bytes(b[8:]), "little")
    print("  %-6s low=0x%016X high=0x%016X" % (name, lo, hi))
