#!/usr/bin/env python3
# anchor_sift - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
#
# Writes the ledger's table of contents into the ledger.
#
#   Usage:  python tools/dev_env/ledger_toc.py [ledger.md]
#
# The ledger is one file of about three thousand lines and every entry opens with a bold lead. That
# is readable end to end and unnavigable, which is what this fixes: every entry, the section it sits
# in, the line it is on, and the day its lead first appeared.
#
# The day comes from ledger_days.tsv, which was computed once from the MMgr history the ledger was
# written in. anchor_sift cannot recompute it, because its own history begins at a single commit, so
# that file is the record and not a cache. An entry the file does not know is new and reports as the
# date this runs.
#
# Line numbers shift when the contents are inserted, so the block is built twice: once to learn how
# tall it is, and once with every line number moved by that height. A number here is exact or it is
# worse than nothing, because a reader who jumps to it and lands somewhere else stops trusting the
# rest of the file.

import datetime
import os
import re
import sys

OPEN = "<!-- BEGIN GENERATED ledger_toc -->"
CLOSE = "<!-- END GENERATED ledger_toc -->"

LEAD = re.compile(r"^\*\*(.+?)\*\*")
SECTION = re.compile(r"^(#{2,3})\s+(.*)$")

HEADER = ("Purpose:", "Scope:", "Author:", "Date:", "Copyright:", "License:")
KEY_WIDTH = 40

HERE = os.path.dirname(os.path.abspath(__file__))
DAYS = os.path.join(HERE, "ledger_days.tsv")


def key_of(lead):
    return lead[:KEY_WIDTH].lower()


def usable(lead):
    """A real entry lead: long enough to be one, and not part of the document head."""
    if len(lead) < 15:
        return False
    return not lead.startswith(HEADER)


def first_seen():
    """Lead key to the day it first appeared."""
    held = {}
    if not os.path.isfile(DAYS):
        return held
    with open(DAYS, encoding="utf-8") as handle:
        next(handle, None)
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 3:
                held[key_of(parts[2])] = parts[0]
    return held


def stripped(lines):
    """The ledger with any previous contents block removed."""
    out = []
    inside = False
    for line in lines:
        if line.strip() == OPEN:
            inside = True
            continue
        if line.strip() == CLOSE:
            inside = False
            continue
        if not inside:
            out.append(line)
    return out


def entries(lines):
    """Every entry in order: its line in this list, the section over it, and its lead."""
    found = []
    section = ""
    for at, line in enumerate(lines, start=1):
        head = SECTION.match(line)
        if head:
            section = head.group(2).strip()
            continue
        hit = LEAD.match(line)
        if hit:
            lead = hit.group(1).strip()
            if usable(lead):
                found.append((at, section, lead))
    return found


def where_to_insert(lines):
    """Above the first top level section, which puts the contents under the document head."""
    for at, line in enumerate(lines):
        if line.startswith("## "):
            return at
    return len(lines)


def build(found, days, today, shift):
    """The contents block, with every line number moved by shift."""
    out = [OPEN, ""]
    out.append("## Contents")
    out.append("")
    out.append("Generated by `tools/dev_env/ledger_toc.py`. Every entry, the line it is on, and the "
               "day its lead first appeared. The days come from the history this ledger was written "
               "in and are a record, not a guess.")
    out.append("")

    counts = {}
    for _, _, lead in found:
        when = days.get(key_of(lead), today)
        counts[when] = counts.get(when, 0) + 1
    out.append("| day | entries |")
    out.append("|---|---|")
    for when in sorted(counts):
        out.append("| %s | %d |" % (when, counts[when]))
    out.append("")

    section = None
    for at, where, lead in found:
        if where != section:
            section = where
            out.append("")
            out.append("**%s**" % (section or "(no section)"))
            out.append("")
            out.append("| day | line | entry |")
            out.append("|---|---|---|")
        when = days.get(key_of(lead), today)
        out.append("| %s | %d | %s |" % (when, at + shift, lead))

    out.append("")
    out.append(CLOSE)
    return out


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        HERE, "..", "..", "docs", "research", "anchor-sift-ledger.md")

    with open(path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()

    body = stripped(lines)
    found = entries(body)
    days = first_seen()
    today = datetime.date.today().isoformat()
    at = where_to_insert(body)

    # First pass learns the height. Every entry sits below the insertion point, so every line
    # number moves by the block plus the blank line written after it. The row count does not
    # depend on the shift, so the second block is the same height as the first.
    trial = build(found, days, today, 0)
    shift = len(trial) + 1
    block = build(found, days, today, shift)
    if len(block) != len(trial):
        raise SystemExit("  contents changed height between passes, line numbers would be wrong")

    out = body[:at] + block + [""] + body[at:]
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")

    print("  %d entries, contents is %d lines" % (len(found), len(block)))
    for when in sorted(set(days.get(key_of(one[2]), today) for one in found)):
        print("    %s" % when)
    print("  written to %s" % os.path.normpath(path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
