# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational")
import os
import random

POLYNOMIAL = 0xC96C5795D7870F42
MASK = (1 << 64) - 1
CHECK = 0x995DC9BBDF1939FA
POWERS = 48
HERE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "engine_v2", "crc")

table = []
for byte in range(256):
    crc = byte
    for _ in range(8):
        crc = ((crc >> 1) ^ POLYNOMIAL) if (crc & 1) else (crc >> 1)
    table.append(crc)


def step(crc, byte):
    return table[(crc ^ byte) & 0xFF] ^ (crc >> 8)


def carry(crc, data):
    for byte in data:
        crc = step(crc, byte)
    return crc


def apply(columns, value):
    out = 0
    for column in range(64):
        if (value >> column) & 1:
            out ^= columns[column]
    return out


advance = [[step(1 << column, 0) for column in range(64)]]
for power in range(1, POWERS):
    before = advance[-1]
    advance.append([apply(before, before[column]) for column in range(64)])


def across(value, count):
    power = 0
    while count:
        if count & 1:
            value = apply(advance[power], value)
        count >>= 1
        power += 1
    return value


assert carry(MASK, b"123456789") ^ MASK == CHECK
for count in (1, 2, 3, 5, 127, 128, 129, 1000, 4096, 65537):
    assert across(0x0123456789ABCDEF, count) == carry(0x0123456789ABCDEF, bytes(count))
chance = random.Random(20260921)
for _ in range(64):
    left = bytes(chance.randrange(256) for _ in range(chance.randrange(1, 300)))
    right = bytes(chance.randrange(256) for _ in range(chance.randrange(1, 300)))
    assert carry(0, left + right) == across(carry(0, left), len(right)) ^ carry(0, right)
message = bytes(chance.randrange(256) for _ in range(1000))
assert carry(MASK, message) ^ MASK == (carry(0, message) ^ across(MASK, len(message))) ^ MASK


def rows(values, per_line, indent):
    lines = []
    for at in range(0, len(values), per_line):
        lines.append(indent + ", ".join("0x%016XULL" % value for value in values[at:at + per_line]))
    return (",\n").join(lines)


out = []
out.append("/* cell_tracking - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>")
out.append(" * SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational")
out.append(" *")
out.append(" * Every use falls under AGPL-3.0-or-later unless you hold explicit permission, which is either a")
out.append(" * negotiated commercial licensing contract or an educator's license issued to you personally.")
out.append(" */")
out.append("/**")
out.append(" * @file crc_key.h")
out.append(" * @brief The CRC-64/XZ key: the byte table, and the register's advance across 2^k zero bytes for k below")
out.append(" *        CRC_KEY_POWERS, each as the 64 columns of a bit matrix over GF(2).")
out.append(" * @author dstroy0 (Douglas Quigg) <dquigg123@gmail.com>")
out.append(" * @date 2026-09-21")
out.append(" *")
out.append(" * GENERATED by maint/emit_crc_key.py, which checks the key before writing it. Do not edit by hand; edit the")
out.append(" * script and emit again.")
out.append(" */")
out.append("#ifndef CRC_KEY_H")
out.append("#define CRC_KEY_H")
out.append("")
out.append("/** @brief Advance operators in the key: across 2^0 to 2^%d zero bytes. */" % (POWERS - 1))
out.append("#define CRC_KEY_POWERS %du" % POWERS)
out.append("")
out.append("/** @brief Byte b's contribution to the register: b pushed through eight shifts of the reflected polynomial. */")
out.append("#define CRC_KEY_TABLE \\")
out.append("    { \\")
out.append(rows(table, 4, "        ").replace(",\n", ", \\\n") + " \\")
out.append("    }")
out.append("")
out.append("/** @brief Column c of operator k: the register holding only bit c, carried across 2^k zero bytes. */")
out.append("#define CRC_KEY_ADVANCE \\")
out.append("    { \\")
blocks = []
for power in range(POWERS):
    blocks.append("        { \\\n" + rows(advance[power], 4, "            ").replace(",\n", ", \\\n") + " \\\n        }")
out.append((", \\\n").join(blocks) + " \\")
out.append("    }")
out.append("")
out.append("#endif /* CRC_KEY_H */")
with open(os.path.join(HERE, "crc_key.h"), "w", encoding="utf-8", newline="\n") as target:
    target.write("\n".join(out) + "\n")
print("crc_key.h written: %d table entries, %d advance operators, every check held" % (len(table), POWERS))
