#!/usr/bin/env python3
# anchor_sift - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
#
# A generated region is reported and attributed, never skipped.
#

import re



# --------------------------------------------------------------------
# GENERATED REGIONS
# --------------------------------------------------------------------
#
# REPORTED AND ATTRIBUTED, NEVER SUPPRESSED, and this is the single decision in this section a
# reader is likely to want to reverse. Here is the evidence against reversing it.
#
# ProtoCore's README.md and TOOLS.md carry BEGIN and END GENERATED marker pairs, 20 pairs across 11
# tracked files, and CI regenerates them on push to main. An edit inside one is reverted by the next
# regeneration: the gate reports a fix, the fix disappears, and the finding comes back forever. That
# argues for skipping the region, and it is the wrong move.
#
# THE TREE SAYS WHY. The single genuine structural finding in the whole of ProtoCore/docs is an
# empty table at docs/README.md:2404, and the region from :2399 to :2408 is generated by
# tools/ci_tooling/generate/gen_readme_sections.py. A rule that skips marked regions deletes the one
# finding worth having in that tree and reports it clean. The generator emits a header and a
# separator with no rows under them, unconditionally. Every CI regeneration republishes an empty
# table on a public README. That is a generator defect, a person has to fix it in the generator, and
# the finding is how they find out.
#
# A FINDING INSIDE A MARKED REGION THEREFORE KEEPS ITS PLACE IN THE COUNT and carries the
# generator's name with it. The marker already holds the generator. The attribution is read from the
# document and cannot go stale. What the region buys is an error: a rewrite never goes inside one,
# because writing there is writing to a file CI overwrites.
#
# AND A SOURCE FIX IS PAIRED WITH REGENERATION. ProtoCore's docs/features.html is generated from
# docs/FEATURES.md by tools/ci_tooling/generate/gen_features_page.py, which writes its OUT at that
# file's :24, and CI gates on `ci gen --check` per tools/harness.py:1330. Fixing the source without
# rerunning the generator reds the pull request that carried the fix. Skipping the generated copy is
# necessary and it is not sufficient. The error below names the generator and says to run it.
#
# AN UNCLOSED MARKER IS ITSELF REPORTED. A BEGIN with no END would otherwise annotate the rest of
# the file as generated, the fail-open shape this whole section exists against.
GENERATED_OPEN = re.compile(r"<!--\s*BEGIN GENERATED\b\s*(?P<label>[^>]*?)\s*-->")
GENERATED_CLOSE = re.compile(r"<!--\s*END GENERATED\b")
GENERATED_BY = re.compile(r"\(([^)]+)\)\s*$")


def generated_regions(lines):
    """({line number: generator}, [(line number, complaint)]) for one document.

    The generator is the parenthesized tail of the BEGIN marker where there is one, and the marker's
    label otherwise. ProtoCore writes both shapes: docs/README.md:2399 names a path and
    test/README.md:72 names a command to run instead.
    """
    inside = {}
    complaints = []
    opened_at = None
    generator = None
    for at, line in enumerate(lines):
        hit = GENERATED_OPEN.search(line)
        if hit:
            if opened_at is not None:
                complaints.append(
                    (
                        opened_at + 1,
                        "BEGIN GENERATED with no END GENERATED under it, and a second "
                        "BEGIN at line %d" % (at + 1),
                    )
                )
            label = hit.group("label").strip()
            named = GENERATED_BY.search(label)
            generator = (
                named.group(1).strip() if named else (label or "an unnamed generator")
            )
            opened_at = at
            continue
        if GENERATED_CLOSE.search(line):
            opened_at = None
            generator = None
            continue
        if opened_at is not None:
            inside[at + 1] = generator
    if opened_at is not None:
        complaints.append(
            (
                opened_at + 1,
                "BEGIN GENERATED with no END GENERATED anywhere under it. Every line "
                "to the end of the file reads as generated",
            )
        )
    return inside, complaints
