#!/usr/bin/env python3
# anchor_sift - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
# Catalog: PRO-RULES-FAMILY
#
# GENERATED by examples/proteins/derive_family_rules.py. Do not edit by hand;
# regenerate from the corpus. Each family is a soft partition of a helix-rich to
# sheet-rich continuum, not a discrete kind; the generator's positive control and
# gap statistic are what license reading these as families at all.
#
# Derived from 2838 deposits (2836 with a usable signature) at a 10-degree grid.

GRID_DEGREES = 10
CELLS_PER_AXIS = 36

# One entry per emergent family. `quirks` is (cell, family_fraction, corpus_fraction, excess),
# the grid cells where the family sits more than the whole corpus does, most in excess first.
FAMILIES = [
    {"members": 811, "quirks": [
        (211, 0.0212, 0.0112, 0.0101),
        (246, 0.0187, 0.0102, 0.0085),
        (212, 0.0161, 0.0081, 0.008),
        (175, 0.0152, 0.008, 0.0072),
        (210, 0.015, 0.008, 0.007),
        (247, 0.017, 0.01, 0.007),
        (248, 0.0122, 0.0065, 0.0057),
        (176, 0.0127, 0.0072, 0.0055),
    ]},
    {"members": 1630, "quirks": [
        (409, 0.098, 0.0861, 0.0119),
        (410, 0.0639, 0.0593, 0.0046),
        (445, 0.0455, 0.0412, 0.0043),
        (446, 0.0167, 0.0153, 0.0014),
        (303, 0.0067, 0.0059, 0.0008),
        (373, 0.0166, 0.0159, 0.0007),
        (414, 0.0037, 0.0031, 0.0006),
        (339, 0.0085, 0.008, 0.0005),
    ]},
    {"members": 395, "quirks": [
        (409, 0.1976, 0.0861, 0.1115),
        (410, 0.1254, 0.0593, 0.0661),
        (445, 0.0925, 0.0412, 0.0514),
        (374, 0.0382, 0.0222, 0.016),
        (446, 0.0301, 0.0153, 0.0148),
        (373, 0.0289, 0.0159, 0.0129),
        (408, 0.0224, 0.0122, 0.0102),
        (444, 0.0213, 0.0121, 0.0092),
    ]},
]


def cell_of(phi_degrees, psi_degrees):
    """The grid cell a (phi, psi) in degrees falls in, wrapping both axes."""
    side = CELLS_PER_AXIS
    cp = int((phi_degrees + 180) // GRID_DEGREES) % side
    cq = int((psi_degrees + 180) // GRID_DEGREES) % side
    return cp * side + cq
