#!/usr/bin/env python3
# anchor_sift - Copyright (C) 2026 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Commercial OR LicenseRef-Educational
"""Impartial games as points carrying values: a position index, and the Grundy value sitting on it.

The arithmetic inside is a minimum excludant over a reachable set, which is four lines. What makes
this a subject is what the values mean and where the answers come from. A finite subtraction game's
Grundy sequence is eventually periodic, proved, with the period a quantity a separate exact routine
computes and not one this work chose. Nim's losing positions are the ones whose heap sizes exclusive
or to zero, which is Bouton's from 1901. Wythoff's are the pairs built from the golden ratio, which
is Wythoff's from 1907.

Those are the reason this subject exists. The domain supplies an arbitrary number of instances, each
with an answer nobody here derived, and the arithmetic to generate one is free. Every other set in
this work either cost money and a database to obtain or has no published answer at all.
"""

import math

# Positions generated for a one dimensional game unless a caller says otherwise. Long enough that a
# subtraction game with a period near thirty still shows dozens of repeats past its preperiod.
POSITIONS = 4096

# Heap sizes per axis for a multi-heap game. 64 keeps a three axis grid at 262144 cells.
HEAP = 64


def grundy_subtraction(moves, positions=POSITIONS):
    """Grundy values of the subtraction game with move set `moves`, from position 0 upward.

    A player takes any number in `moves` from a single heap and whoever cannot move loses. The value
    at n is the least non-negative integer absent from the values of the positions reachable from n.
    Zero marks a position whose mover loses.
    """
    least = sorted(set(int(move) for move in moves if int(move) > 0))
    out = []
    for size in range(positions):
        seen = set()
        for move in least:
            if move > size:
                break
            seen.add(out[size - move])
        value = 0
        while value in seen:
            value += 1
        out.append(value)
    return out


def subtraction_period(values, preperiod_cap=None):
    """The exact period of a Grundy sequence, and where it starts, found by comparison and not by a
    measurement.

    This is the outside answer every measured row in this subject is scored against, so it is
    deliberately dull: it slides a window over the tail and returns the shortest shift the sequence
    repeats under, checked to the end. Returns (period, start), or (None, None) where the sequence
    does not settle inside what it was handed.

    The theorem underneath is that a subtraction game with a finite move set has an eventually
    periodic Grundy sequence, with period and preperiod both bounded. This routine finds that period;
    it does not assume one exists, and it reports None rather than a guess where none is visible.
    """
    length = len(values)
    if length < 16:
        return None, None
    cap = preperiod_cap if preperiod_cap is not None else (length // 2)

    for period in range(1, (length // 4) + 1):
        for start in range(0, min(cap, length - (3 * period))):
            if all(values[index] == values[index + period]
                   for index in range(start, length - period)):
                return period, start
    return None, None


def nim_losses(heaps=3, heap=HEAP):
    """The win and loss grid of multi-heap Nim, as a flat list over the product of the heap sizes.

    Cell value is 0 where the position loses for the player to move and 1 where it wins. Bouton
    proved in 1901 that the losing positions are exactly those whose heap sizes exclusive or to
    zero, so this grid is generated from that theorem and is not a search. Reading a period back off
    it is therefore scored against an answer that is a hundred and twenty five years old.
    """
    out = bytearray(heap ** heaps)
    index = 0
    for cell in range(heap ** heaps):
        rest = cell
        total = 0
        for _ in range(heaps):
            total ^= rest % heap
            rest //= heap
        out[index] = 0 if total == 0 else 1
        index += 1
    return out


def wythoff_losses(heap=HEAP):
    """The win and loss grid of Wythoff's game, flattened row major over `heap` by `heap`.

    A player takes any number from one heap, or the same number from both. Wythoff showed in 1907
    that the losing positions are the pairs (floor(n*phi), floor(n*phi^2)) and their mirrors, which
    is the reason this sits beside Nim: the same shape of game with an answer that has no period in
    it at all. A detector that reads a period off Nim and reads one off this too is reporting an
    artefact.

    Generated by the mex recursion and not from the formula, so the grid is independent of the
    closed form it is later checked against.
    """
    grid = bytearray(heap * heap)
    for left in range(heap):
        for right in range(heap):
            losing = True
            for take in range(1, left + 1):
                if grid[((left - take) * heap) + right] == 0:
                    losing = False
                    break
            if losing:
                for take in range(1, right + 1):
                    if grid[(left * heap) + (right - take)] == 0:
                        losing = False
                        break
            if losing:
                for take in range(1, min(left, right) + 1):
                    if grid[((left - take) * heap) + (right - take)] == 0:
                        losing = False
                        break
            grid[(left * heap) + right] = 0 if losing else 1
    return grid


def wythoff_pairs(count=32):
    """The published closed form for Wythoff's losing positions, from the golden ratio.

    Kept apart from `wythoff_losses` on purpose. One is the game played out and the other is the
    1907 answer, and a check that they agree is a check and not a definition.
    """
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    return [(int(math.floor(n * phi)), int(math.floor(n * phi * phi)))
            for n in range(count)]
