"""Generates the book's bibliography from the citations registry, pinned to a commit.

A surname in a chapter tells a reader which idea is being used and gives them nothing to go and
read. This turns the registry next door into a bibliography, and pins it: every entry carries the
commit of anchor_sift_citations it was read from, and the SHA-256 of the held copy where there is
one. A reader who disagrees with a number can then ask which bytes it was checked against and get
an exact answer.

The registry is the single source of truth. Nothing bibliographic is written here, because a second
copy of a citation is a second thing to keep true and the two would drift.

    python maint/texbuild/build_bibliography.py

Finds the registry through ANCHOR_SIFT_CITATIONS, else beside the checkouts. Refuses to generate
from a dirty or unpushed registry, because a pin to a commit nobody else can fetch is not a pin.
"""

import io
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
TARGET = os.path.join(ROOT, "theory", "theory", "cryptography", "sha256", "chapters", "chapter_sources.tex")

# Only rows the SHA-256 work actually cites. The registry also serves anchor sift, and a
# bibliography listing sources this book never mentions would be padding.
# A selector matched against the rows of the shared registry, and never a path to open, so it has
# to read the same as whatever the rows were tagged with. Derived from the directory this tree
# actually sits in instead of spelled out, which keeps it correct if the tree is renamed and keeps
# the name itself out of the source.
MINE = "repos/" + os.path.basename(ROOT)


def find_registry():
    named = os.environ.get("ANCHOR_SIFT_CITATIONS")
    if named and os.path.isdir(named):
        return named
    guess = os.path.abspath(os.path.join(ROOT, "..", "..", "..",
                                         "private_repos", "anchor_sift_citations"))
    if os.path.isdir(guess):
        return guess
    return None


def git(repo, *args):
    return subprocess.check_output(("git", "-C", repo) + args).decode().strip()


def escape(text):
    """LaTeX-safe. Titles carry colons and hyphens; authors carry accents that fontspec handles."""
    for bad, good in (("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"), ("$", "\\$"),
                      ("#", "\\#"), ("_", "\\_"), ("{", "\\{"), ("}", "\\}"), ("~", "\\textasciitilde{}"),
                      ("^", "\\textasciicircum{}")):
        text = text.replace(bad, good)
    return text


def read_table(path):
    rows = []
    with io.open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.rstrip("\n")
            if (not line.strip()) or line.startswith("#"):
                continue
            parts = line.split("\t")
            if parts[0] in ("key", "sha256"):
                continue
            rows.append(parts)
    return rows


def main():
    registry = find_registry()
    if registry is None:
        sys.stderr.write("no citations registry; set ANCHOR_SIFT_CITATIONS\n")
        return 1

    if git(registry, "status", "--porcelain"):
        sys.stderr.write("the registry has uncommitted changes; commit and sign it first\n")
        return 1

    commit = git(registry, "rev-parse", "HEAD")
    try:
        remote = git(registry, "rev-parse", "origin/main")
    except subprocess.CalledProcessError:
        remote = None
    if remote != commit:
        sys.stderr.write("the registry commit is not pushed; a pin nobody can fetch is not a pin\n")
        return 1

    when = git(registry, "show", "-s", "--format=%cs", "HEAD")

    held = {}
    for row in read_table(os.path.join(registry, "MANIFEST.tsv")):
        while len(row) < 4:
            row.append("")
        held[row[3]] = row[0]

    sources = []
    for row in read_table(os.path.join(registry, "SOURCES.tsv")):
        while len(row) < 9:
            row.append("")
        if MINE not in row[8]:
            continue
        sources.append({
            "key": row[0], "author": row[2], "year": row[3],
            "title": row[4], "identifier": row[5], "file": row[6],
        })
    sources.sort(key=lambda s: s["key"].lower())

    looked_up = [s for s in sources if s["author"] or s["identifier"]]
    unlooked = [s for s in sources if not (s["author"] or s["identifier"])]

    out = []
    out.append("% Generated by maint/texbuild/build_bibliography.py from the citations registry.")
    out.append("% Do not edit: the registry is the source of truth and this would drift from it.")
    out.append("\\chapter{Sources}")
    out.append("")
    out.append("Every measurement in this work is built on somebody's published result, and the")
    out.append("first purpose of this chapter is that those people are credited by name. A surname")
    out.append("in a footnote is not a citation. The second purpose is that the credit is checkable:")
    out.append("each source is registered in \\texttt{anchor\\_sift\\_citations}, which holds the copy")
    out.append("itself, and this bibliography is generated from that registry and pinned to one")
    out.append("commit of it, so a reference resolves not to a title but to exact bytes.")
    out.append("")
    out.append("Credit here does not depend on agreement. Where this work reproduces a published")
    out.append("result it says so, and where it fails to reproduce one it says that too, under the")
    out.append("same names --- a refutation rests on the original as much as a confirmation does.")
    out.append("")
    out.append("\\begin{description}")
    out.append("\\item[Registry commit] \\texttt{%s}" % escape(commit))
    out.append("\\item[Dated] %s" % escape(when))
    out.append("\\item[Inventory] \\texttt{MANIFEST.tsv}, signed; the hashes below are its rows")
    out.append("\\end{description}")
    out.append("")
    out.append("A reader who disagrees with a number in this book can ask which copy it was checked")
    out.append("against, and the hash answers exactly. Two copies of a paper are rarely the same")
    out.append("bytes.")
    out.append("")

    if looked_up:
        out.append("\\section{Read, and held}")
        out.append("")
        for s in looked_up:
            out.append("\\subsection*{%s}" % escape(s["key"]))
            out.append("\\begin{description}")
            if s["author"]:
                out.append("\\item[Authors] %s" % escape(s["author"]))
            if s["year"]:
                out.append("\\item[Year] %s" % escape(s["year"]))
            if s["title"]:
                out.append("\\item[Title] \\emph{%s}" % escape(s["title"]))
            if s["identifier"]:
                out.append("\\item[Identifier] \\texttt{%s}" % escape(s["identifier"]))
            if s["file"]:
                digest = held.get(s["file"], "")
                out.append("\\item[Copy held] \\texttt{%s}" % escape(s["file"]))
                if digest:
                    out.append("\\item[SHA-256] {\\footnotesize\\texttt{%s}}" % escape(digest))
            else:
                out.append("\\item[Copy held] none. The publisher declines automated retrieval and "
                           "was not pressed.")
            out.append("\\end{description}")
            out.append("")

    if unlooked:
        out.append("\\section{Owed a full citation}")
        out.append("")
        out.append("These results are used in the work and their authors are not yet properly")
        out.append("credited: the registry holds a key and no bibliographic fields. That is a debt")
        out.append("rather than a category, and it is listed here so it stays visible.")
        out.append("")
        out.append("The fields are filled in by hand from the source itself, because a surname cannot")
        out.append("be turned into a reference by a heuristic and \\textbf{a guessed citation is worse")
        out.append("than an empty one} --- it credits the wrong person, or the right person for the")
        out.append("wrong thing, and reads as though somebody checked.")
        out.append("")
        out.append("\\begin{itemize}")
        for s in unlooked:
            out.append("\\item %s" % escape(s["key"]))
        out.append("\\end{itemize}")
        out.append("")

    with io.open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")

    print("wrote %s" % os.path.relpath(TARGET, ROOT))
    print("  pinned to %s (%s)" % (commit[:12], when))
    print("  %d read and held, %d cited but not yet read" % (len(looked_up), len(unlooked)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
